# Generated by Django 3.2.5 on 2024-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='consent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_be_contacted',
            field=models.BooleanField(default=False, verbose_name='Allowed contact'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_be_shared',
            field=models.BooleanField(default=False, verbose_name='Share data consent'),
        ),
    ]
