# Generated by Django 3.2.5 on 2024-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_auto_20240124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
