# Generated by Django 5.0.1 on 2024-02-13 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Nom"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("back-end", "back-end"),
                            ("front-end", "front-end"),
                            ("IOS", "IOS"),
                            ("Android", "Android"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contributor",
                    models.ManyToManyField(
                        related_name="contributors", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
