# Generated by Django 5.0.1 on 2024-02-13 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0008_alter_project_contributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contributor",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
