# Generated by Django 5.0.1 on 2024-02-14 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0010_alter_project_contributor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="contributor",
            new_name="contributors",
        ),
    ]
