# Generated by Django 5.0.1 on 2024-03-04 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0011_rename_contributor_project_contributors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="birth_day",
            new_name="birthday",
        ),
        migrations.AlterField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="contributions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
