# Generated by Django 5.0.1 on 2024-03-12 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0013_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="assigned_contributor",
            new_name="author",
        ),
    ]
