# Generated by Django 5.0.1 on 2024-03-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0014_rename_assigned_contributor_issue_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="softdesk.project",
            ),
            preserve_default=False,
        ),
    ]
