# Generated by Django 5.0.1 on 2024-03-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0015_issue_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                ],
                default="To Do",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[("BUG", "BUG"), ("FEATURE", "FEATURE"), ("TASK", "TASK")],
                default=None,
                max_length=50,
            ),
        ),
    ]
