# Generated by Django 5.0.1 on 2024-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0017_issue_assigned_contributor_alter_issue_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues_list",
                to="softdesk.project",
            ),
        ),
    ]
