# Generated by Django 5.0.1 on 2024-03-26 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0019_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="issue",
            new_name="issue_ref",
        ),
    ]
