# Generated by Django 5.0.1 on 2024-03-26 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk", "0020_rename_issue_comment_issue_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
